import React from 'react'

const Head = () =>{
    return (
        <>
            <title>Sistema Ola Mundo!</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"></meta>
            <meta name="description" content="Generated by create nextjs app"></meta>
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}

export default Head