import NavLink from "./nav-link"
import './global.css'
import Head from "./head"

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  }: {
  children: React.ReactNode
}) {

  return (
    <html className='bg-gray-800 text-gray-100' lang="en">
      <Head/> 
      <body>
        <h1> Sistema: Olá Mundo </h1>
        <header className="border-b p-4">
          <nav className="space-x-4">
            <NavLink href="/">Home</NavLink>  
            <NavLink href="/dashboard">Dashboard</NavLink>  
            <NavLink href="/cadastro">Cadastro</NavLink>  
            <NavLink href="/users">Usuários</NavLink>
            <NavLink href="/conect">Conect</NavLink>   
            <NavLink href="/login">Login</NavLink>  
          </nav>  
          <hr/>
        </header> 
        <main className='p-4'>
          {children}
        </main>
       
      </body>
    </html>
  )
}
